import type { Category, CategoryWord, Difficulty } from "../types";

const RAW_CATEGORIES: Array<{ id: string; name: string; words: string[] }> = [
  {
    id: "animales",
    name: "Animales",
    words: [
      "León",
      "Tigre",
      "Elefante",
      "Jirafa",
      "Cebra",
      "Rinoceronte",
      "Hipopótamo",
      "Cocodrilo",
      "Pingüino",
      "Delfín",
      "Tiburón",
      "Ballena",
      "Águila",
      "Búho",
      "Lobo",
      "Zorro",
      "Oso",
      "Koala",
      "Canguro",
      "Mono",
      "Chimpancé",
      "Gorila",
      "Caballo",
      "Vaca",
      "Oveja",
      "Cabra",
      "Cerdo",
      "Perro",
      "Gato",
      "Conejo",
      "Rata",
      "Murciélago",
      "Serpiente",
      "Tortuga",
      "Camaleón",
      "Rana",
      "Sapo",
      "Abeja",
      "Mariposa",
      "Pulpo"
    ]
  },
  {
    id: "comida",
    name: "Comida",
    words: [
      "Pizza",
      "Hamburguesa",
      "Arepa",
      "Tacos",
      "Burrito",
      "Sushi",
      "Paella",
      "Empanada",
      "Ensalada",
      "Sopa",
      "Pasta",
      "Lasagna",
      "Panqueques",
      "Croissant",
      "Pan",
      "Queso",
      "Yogur",
      "Helado",
      "Chocolate",
      "Café",
      "Té",
      "Jugo",
      "Ceviche",
      "Pollo asado",
      "Carne a la parrilla",
      "Pescado frito",
      "Arroz con pollo",
      "Lentejas",
      "Frijoles",
      "Arequipe",
      "Enchiladas",
      "Ramen",
      "Curry",
      "Guacamole",
      "Gazpacho",
      "Tortilla española",
      "Tamal",
      "Pastel",
      "Donut",
      "Fruta picada"
    ]
  },
  {
    id: "profesiones",
    name: "Profesiones",
    words: [
      "Médico",
      "Enfermera",
      "Profesor",
      "Ingeniero",
      "Arquitecto",
      "Abogado",
      "Psicólogo",
      "Dentista",
      "Veterinario",
      "Cocinero",
      "Mesero",
      "Panadero",
      "Mecánico",
      "Electricista",
      "Plomero",
      "Carpintero",
      "Diseñador",
      "Fotógrafo",
      "Periodista",
      "Piloto",
      "Azafata",
      "Bombero",
      "Policía",
      "Soldado",
      "Juez",
      "Contador",
      "Economista",
      "Programador",
      "Científico",
      "Farmacéutico",
      "Fisioterapeuta",
      "Actor",
      "Músico",
      "Director de cine",
      "Editor",
      "Barbero",
      "Estilista",
      "Florista",
      "Guardabosques",
      "Astrónomo"
    ]
  },
  {
    id: "deportes",
    name: "Deportes",
    words: [
      "Fútbol",
      "Baloncesto",
      "Béisbol",
      "Tenis",
      "Golf",
      "Natación",
      "Atletismo",
      "Ciclismo",
      "Boxeo",
      "MMA",
      "Karate",
      "Judo",
      "Taekwondo",
      "Rugby",
      "Voleibol",
      "Hockey",
      "Surf",
      "Skate",
      "Patinaje artístico",
      "Gimnasia",
      "Escalada",
      "Esgrima",
      "Remo",
      "Canotaje",
      "Triatlón",
      "Maratón",
      "Fórmula 1",
      "Rally",
      "Parkour",
      "Bádminton",
      "Tenis de mesa",
      "Squash",
      "Yoga",
      "Halterofilia",
      "Lucha libre",
      "Pesca deportiva",
      "Snowboard",
      "Esquí",
      "Waterpolo",
      "Cricket"
    ]
  },
  {
    id: "peliculas-series",
    name: "Películas y Series",
    words: [
      "Thriller",
      "Comedia romántica",
      "Ciencia ficción",
      "Fantasía épica",
      "Terror",
      "Western",
      "Animación",
      "Documental",
      "Serie policial",
      "Serie médica",
      "Serie juvenil",
      "Drama histórico",
      "Película de superhéroes",
      "Película de espías",
      "Película de zombis",
      "Película de piratas",
      "Película de viajes en el tiempo",
      "Película de invasión alienígena",
      "Serie de cocina",
      "Serie de abogados",
      "Sitcom",
      "Miniserie",
      "Telenovela",
      "Serie de reality",
      "Película musical",
      "Película de guerra",
      "Película de detectives",
      "Película de aventuras",
      "Película de sobrevivencia",
      "Película postapocalíptica",
      "Serie de misterio",
      "Serie de fantasmas",
      "Película de deportes",
      "Película de carreras",
      "Película biográfica",
      "Película de monstruos",
      "Serie de ciencia",
      "Película de robots",
      "Serie de época",
      "Serie de viajes"
    ]
  },
  {
    id: "lugares",
    name: "Lugares",
    words: [
      "Playa",
      "Montaña",
      "Bosque",
      "Desierto",
      "Isla",
      "Lago",
      "Río",
      "Cascada",
      "Volcán",
      "Cueva",
      "Ciudad",
      "Pueblo",
      "Parque",
      "Museo",
      "Biblioteca",
      "Estadio",
      "Aeropuerto",
      "Estación de tren",
      "Puerto",
      "Mercado",
      "Centro comercial",
      "Teatro",
      "Hospital",
      "Escuela",
      "Universidad",
      "Restaurante",
      "Cafetería",
      "Hotel",
      "Camping",
      "Granja",
      "Fábrica",
      "Oficina",
      "Plaza",
      "Iglesia",
      "Templo",
      "Castillo",
      "Palacio",
      "Mirador",
      "Puerto deportivo",
      "Terminal de buses"
    ]
  },
  {
    id: "objetos",
    name: "Objetos",
    words: [
      "Silla",
      "Mesa",
      "Cama",
      "Lámpara",
      "Reloj",
      "Teléfono",
      "Computador",
      "Teclado",
      "Mouse",
      "Auriculares",
      "Mochila",
      "Botella",
      "Llave",
      "Candado",
      "Libro",
      "Cuaderno",
      "Bolígrafo",
      "Lápiz",
      "Borrador",
      "Regla",
      "Tijeras",
      "Martillo",
      "Destornillador",
      "Taladro",
      "Cuchillo",
      "Olla",
      "Sartén",
      "Taza",
      "Plato",
      "Cuchara",
      "Tenedor",
      "Espejo",
      "Ventilador",
      "Control remoto",
      "Televisor",
      "Sofá",
      "Alfombra",
      "Paraguas",
      "Gafas",
      "Linterna"
    ]
  },
  {
    id: "acciones",
    name: "Acciones y Verbos",
    words: [
      "Correr",
      "Saltar",
      "Caminar",
      "Bailar",
      "Cantar",
      "Reír",
      "Llorar",
      "Gritar",
      "Susurrar",
      "Dibujar",
      "Pintar",
      "Escribir",
      "Leer",
      "Cocinar",
      "Comer",
      "Beber",
      "Dormir",
      "Despertar",
      "Nadar",
      "Volar",
      "Conducir",
      "Navegar",
      "Escalar",
      "Jugar",
      "Construir",
      "Armar",
      "Romper",
      "Arreglar",
      "Comprar",
      "Vender",
      "Buscar",
      "Encontrar",
      "Escuchar",
      "Mirar",
      "Tocar",
      "Empujar",
      "Tirar",
      "Recoger",
      "Plantar",
      "Viajar"
    ]
  },
  {
    id: "tecnologia",
    name: "Tecnología",
    words: [
      "Internet",
      "Servidor",
      "Nube",
      "Datos",
      "Algoritmo",
      "Código",
      "Software",
      "Hardware",
      "Aplicación",
      "Sistema operativo",
      "Base de datos",
      "WiFi",
      "Bluetooth",
      "GPS",
      "Inteligencia artificial",
      "Realidad virtual",
      "Realidad aumentada",
      "Ciberseguridad",
      "Contraseña",
      "Router",
      "Procesador",
      "Memoria RAM",
      "Tarjeta gráfica",
      "Pantalla táctil",
      "Sensor",
      "Drone",
      "Robot",
      "Impresora 3D",
      "API",
      "Bug",
      "Actualización",
      "Firewall",
      "Encriptación",
      "Backup",
      "Criptomoneda",
      "Blockchain",
      "Streaming",
      "Videollamada",
      "Chatbot",
      "Automatización"
    ]
  },
  {
    id: "musica",
    name: "Música",
    words: [
      "Guitarra",
      "Piano",
      "Batería",
      "Bajo",
      "Violín",
      "Saxofón",
      "Trompeta",
      "Flauta",
      "Acordeón",
      "Micrófono",
      "Altavoz",
      "Auriculares",
      "Concierto",
      "Orquesta",
      "Coro",
      "Melodía",
      "Ritmo",
      "Compás",
      "Nota",
      "Partitura",
      "Ensayo",
      "Grabación",
      "Mezcla",
      "DJ",
      "Playlist",
      "Karaoke",
      "Rock",
      "Pop",
      "Salsa",
      "Reggaetón",
      "Jazz",
      "Blues",
      "Clásica",
      "Electrónica",
      "Cumbia",
      "Merengue",
      "Banda sonora",
      "Balada",
      "Percusión",
      "Voz"
    ]
  },
  {
    id: "productos",
    name: "Productos",
    words: [
      "Cepillo de dientes",
      "Pasta dental",
      "Champú",
      "Jabón",
      "Crema facial",
      "Protector solar",
      "Desodorante",
      "Perfume",
      "Detergente",
      "Limpiador multiusos",
      "Toallas de papel",
      "Papel higiénico",
      "Bolsa de basura",
      "Baterías",
      "Bombillo",
      "Cargador",
      "Cable USB",
      "Lata de gaseosa",
      "Botella de agua",
      "Snack",
      "Galletas",
      "Cereal",
      "Leche",
      "Yogur bebible",
      "Salsa de tomate",
      "Mayonesa",
      "Aceite",
      "Sal",
      "Azúcar",
      "Harina",
      "Arroz",
      "Pasta seca",
      "Pan tajado",
      "Mermelada",
      "Queso en lonchas",
      "Café instantáneo",
      "Té en bolsitas",
      "Jabón en polvo",
      "Esponja",
      "Velas"
    ]
  },
  {
    id: "colombia",
    name: "Colombia",
    words: [
      "Bogotá",
      "Medellín",
      "Cali",
      "Barranquilla",
      "Cartagena",
      "Bucaramanga",
      "Pereira",
      "Manizales",
      "Armenia",
      "Cúcuta",
      "Santa Marta",
      "Villavicencio",
      "Pasto",
      "Montería",
      "Ibagué",
      "Popayán",
      "Valle del Cocora",
      "Eje Cafetero",
      "Sierra Nevada",
      "Amazonas",
      "Llanos Orientales",
      "Arepa de huevo",
      "Bandeja paisa",
      "Ajiaco",
      "Sancocho",
      "Lechona",
      "Tamal tolimense",
      "Empanada",
      "Obleas",
      "Pandebono",
      "Buñuelos",
      "Natilla",
      "Café colombiano",
      "Vallenato",
      "Cumbia",
      "Sombrero vueltiao",
      "Carnaval de Barranquilla",
      "San Andrés",
      "Ciudad Perdida",
      "Guatapé"
    ]
  }
];

const AMBIGUOUS_WORDS = new Set(
  [
    "Thriller",
    "Comedia romántica",
    "Ciencia ficción",
    "Fantasía épica",
    "Terror",
    "Animación",
    "Documental",
    "Sitcom",
    "Miniserie",
    "Telenovela",
    "Ciudad",
    "Pueblo",
    "Parque",
    "Mercado",
    "Internet",
    "Datos",
    "Código",
    "Software",
    "Hardware",
    "Aplicación",
    "Rock",
    "Pop",
    "Jazz",
    "Blues",
    "Clásica",
    "Electrónica",
    "Cumbia",
    "Balada"
  ].map((word) => normalizeWord(word))
);

function normalizeWord(value: string): string {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim();
}

function inferDifficulty(word: string): Difficulty {
  const compactLength = word.replace(/\s+/g, "").length;
  if (compactLength <= 6) return "easy";
  if (compactLength <= 11) return "medium";
  return "hard";
}

function toCategoryWord(word: string): CategoryWord {
  const normalized = normalizeWord(word);
  const ambiguous = AMBIGUOUS_WORDS.has(normalized);
  return {
    word,
    difficulty: inferDifficulty(word),
    flags: ambiguous ? { ambiguous: true } : undefined
  };
}

export const DEFAULT_CATEGORIES: Category[] = RAW_CATEGORIES.map((category) => ({
  ...category,
  words: category.words.map(toCategoryWord)
}));
